Grocery/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("dashboard", dashboard,  name ="dashboard"),
    path("user_login", user_login, name="user_login"),
    path("add_user", add_user, name="add_user"),
    path("login", login, name="login"),
    path("user_logout", user_logout, name='user_logout'),

    # category url
    path("addcategory", category.as_view(), name="addcategory"),
    path("viewcategory", viewcategory, name="viewcategory"),

    # products url

    path("products", products.as_view(), name="products"),
    path("viewproducts", viewProducts, name='viewproducts'),
    path("update_product/<int:prodid>", update_product, name='update_product'),
    path("delete_product/<int:id>", delete_product, name='delete_product'),
    path("saveupdate/<int:id>", saveupdate, name='saveupdate'),

]

GroceryApp/urls.py
from django.contrib import admin
from django.urls import *
from django.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path("Grocery/", include('Grocery.urls')),
    path("", include('customer.urls')),


]

Grocery/models.py
from django.db import models
from django.utils.html import format_html


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)
    desc = models.TextField()


    class Meta:
        db_table = 'category'

        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Merchant(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    mobile = models.CharField(max_length=20)
    password = models.CharField(max_length=255)
    shop_name = models.CharField(max_length=255)
    address = models.TextField()
    city = models.CharField(max_length=255)

    class Meta:
        db_table = 'Merchant'

    def __str__(self):
        return self.name


class Products(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.FloatField(max_length=20)
    discount = models.IntegerField()
    image = models.FileField(upload_to='products/')

    Merchant = models.ForeignKey(to=Merchant, on_delete=models.CASCADE)
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'products'
        verbose_name_plural = 'products'

templates/addcategory.html
{% extends 'layout.html' %}
{% load static %}

{% block maincontent %}
    <div class="container">
        <h2 class="text-primary text-center my-2">Add Category</h2>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">{{ message }}</div>

                <button type="button" class="btn-close" data-bs-dismiss=" alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}

    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <form action="{{ request.path }}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for i in form %}
                    <div class="mb-3">
                        {{ i.label_tag }}
                        {{ i }}

                    </div>

                {% endfor %}

                <div class="text-center">
                    <input type="submit" value="Submit" class="btn btn-outline-success w-25 my-2">

                </div>

            </form>
        </div>
    </div>
{% endblock %}

templates/dashboard.html
{% extends 'layout.html' %}
{% load static %}

{% block maincontent %}
    <h2> Hello</h2>

{% endblock %}

templates/deleteitems.html
{% extends 'layout.html' %}
{% load  static %}
{% block maincontent %}
    <div class="container">
        <form action="/delete_product/{{ product.id }}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="mb-3">
                <label for="id_name">Name:</label>
                <input type="text" name="name" value="{{ product.name }}" class="form-control" maxlength="255"
                       required="" id="id_name">

            </div>


            <div class="mb-3">
                <label for="id_description">Description:</label>
                <input type="text" name="description" value="{{ product.description }}" class="form-control" required="" id="id_description">

            </div>


            <div class="mb-3">
                <label for="id_price">Price:</label>
                <input type="text" name="price" value="{{ product.price }}" class="form-control" required="" id="id_price">

            </div>


            <div class="mb-3">
                <label for="id_discount">Discount:</label>
                <input type="text" name="discount" value="{{ product.discount }}" class="form-control" required="" id="id_discount">

            </div>

            <div class="col-sm-8 img-fluid">
                <img src="/static/media/{{ product.image }}" alt="">
            </div>
            <div class="mb-3">
                <label for="id_image">Image:</label>
                <input type="file" name="image" class="form-control" id="id_image">

            </div>


            <div class="text-center">
                <input type="submit" value="Submit" class="btn btn-outline-success w-25 my-2">

            </div>

        </form>
    </div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>pageTitle</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        {% if request.session.user %}
            <a class="navbar-brand" href="{% url 'user_login' %}">{{ request.session.user.name }}</a>

        {% endif %}
        <a class="navbar-brand" href="{% url 'user_login' %}">HOME</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">

                <li class="nav-item">
                    <a class="nav-link active" href="#">Contact Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="#">About Us</a>
                </li>


                {% if request.session.user %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdownMenuLink" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Products
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="{% url 'products' %}">Add Products</a></li>
                            <li><a class="dropdown-item" href="{% url 'viewproducts' %}">View Products</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdownMenuLink" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Categories
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="{% url 'addcategory' %}">Add Category</a></li>
                            <li><a class="dropdown-item" href="{% url 'viewcategory' %}">View Category</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'user_logout' %}">Log Out</a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>

{% block maincontent %}

{% endblock %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
</body>
</html>

templates/products.html
{% extends 'layout.html' %}
{% load static %}

{% block maincontent %}
    <div class="container">
        <h2 class="text-primary text-center my-2">Add Products</h2>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">{{ message }}

                    <button type="button" class="btn-close" data-bs-dismiss=" alert" aria-label="Close"></button>
                </div>
                </div>
            {% endfor %}
        {% endif %}

    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <form action="{{ request.path }}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for i in forms %}
                    <div class="mb-3">
                        {{ i.label_tag }}
                        {{ i }}

                    </div>

                {% endfor %}
                <input type="hidden" id="merchant" name="Merchant_id" value="{{ request.session.user.id }}">
                <div class="text-center">
                    <input type="submit" value="Submit" class="btn btn-outline-success w-25 my-2">

                </div>

            </form>
        </div>
    </div>



{% endblock %}

templates/updatecategory.html
{% extends 'layout.html' %}
{% load static %}

{% block maincontent %}
    <div class="container">
        <h2 class="text-primary text-center my-2">Add Category</h2>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">{{ message }}</div>

                <button type="button" class="btn-close" data-bs-dismiss=" alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}

    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <form action="{{ request.path }}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for i in form %}
                    <div class="mb-3">
                        {{ i.label_tag }}
                        {{ i }}

                    </div>

                {% endfor %}

                <div class="text-center">
                    <input type="submit" value="Submit" class="btn btn-outline-success w-25 my-2">

                </div>

            </form>
        </div>
    </div>
{% endblock %}

templates/updateitems.html
{% extends 'layout.html' %}
{% load  static %}
{% block maincontent %}
    <div class="container">
        <form action="/saveupdate/{{ product.id }}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="mb-3">
                <label for="id_name">Name:</label>
                <input type="text" name="name" value="{{ product.name }}" class="form-control" maxlength="255"
                       required="" id="id_name">

            </div>


            <div class="mb-3">
                <label for="id_description">Description:</label>
                <input type="text" name="description" value="{{ product.description }}" class="form-control" required="" id="id_description">

            </div>


            <div class="mb-3">
                <label for="id_price">Price:</label>
                <input type="text" name="price" value="{{ product.price }}" class="form-control" required="" id="id_price">

            </div>


            <div class="mb-3">
                <label for="id_discount">Discount:</label>
                <input type="text" name="discount" value="{{ product.discount }}" class="form-control" required="" id="id_discount">

            </div>

            <div class="col-sm-8 img-fluid">
                <img src="/static/media/{{ product.image }}" alt="">
            </div>
            <div class="mb-3">
                <label for="id_image">Image:</label>
                <input type="file" name="image" class="form-control" id="id_image">

            </div>


            <div class="text-center">
                <input type="submit" value="Submit" class="btn btn-outline-success w-25 my-2">

            </div>

        </form>
    </div>
{% endblock %}

templates/user_login.html
{% extends 'layout.html' %}
{% load static %}
{% block maincontent %}


    <div class="row">
        <h1 class="text-center text-primary my-2">Merchant Registration and Login</h1>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            </ul>
        {% endif %}
        <div class="col-sm-5 my-3 offset-1">
            <form action="/Grocery/add_user" method="post">
                {% csrf_token %}

                <h2 class="text-center text-primary">Register</h2>
                <div>
                    <label for="name">ENTER FULL NAME</label>
                    <input type="text" name="name" id="name" class="form-control my-2">
                </div>

                <div>
                    <label for="email">ENTER EMAIL</label>
                    <input type="text" name="email" id="email" class="form-control my-2">
                </div>
                <div>
                    <label for="mobile">ENTER MOBILE</label>
                    <input type="tel" name="mobile" id="mobile" class="form-control my-2">
                </div>
                <div>
                    <label for="password">ENTER PASSWORD</label>
                    <input type="password" name="password" id="password" class="form-control my-2">
                </div>
                <div>
                    <label for="shop_name">ENTER SHOP NAME</label>
                    <input type="text" name="shop_name" id="shop_name" class="form-control my-2">
                </div>
                <div>
                    <label for="address">ADDRESS</label>
                    <textarea name="address" id="address" cols="30" rows="3" class="form-control my-2"></textarea>
                </div>
                <div>
                    <label for="city">ENTER CITY</label>
                    <input type="text" name="city" id="city" class="form-control my-2">
                </div>
                <div class="text-center">
                    <input type="submit" value="Submit" class="btn btn-outline-primary w-25 my-2">
                </div>

            </form>
        </div>
        <div class="col-sm-5 my-3">
            <form action="/Grocery/login" method="post">
                {% csrf_token %}

                <h2 class="text-center text-primary">Login</h2>
                <div>
                    <label for="email">ENTER EMAIL</label>
                    <input type="email" name="email" id="email" class="form-control my-2">
                </div>
                <div>
                    <label for="password">ENTER PASSWORD</label>
                    <input type="password" id="password" name="password" class="form-control my-2">
                </div>
                <div class="text-center">
                    <input type="submit" value="Submit" class="btn btn-outline-primary w-25 my-2">
                </div>
            </form>
        </div>
    </div>




{% endblock %}

templates/viewCategory.html
{% extends 'layout.html' %}
{% load static %}

{% block maincontent %}
    <div class="container">
        <h2 class="text-center my-5 text-primary">View Category</h2>

        <table class="table table-hover table-light">
            <thead>
            <tr>

                <th>Name</th>
                <th>Description</th>


            </tr>
            </thead>
            <tbody>
            {% for i in viewcategory %}
                <tr>
                    <td>{{ i.name }}</td>
                    <td>{{ i.desc }}</td>


                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

##testing git

templates/viewProducts.html
{% extends 'layout.html' %}
{% load static %}

{% block maincontent %}
    <div class="container">
        <h2 class="text-center my-5">View Products</h2>

        <table class="table table-hover table-light">
            <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Price</th>
                <th>Discount</th>
                <th>Merchant ID</th>
                <th>Image</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            {% for i in viewproducts %}
                <tr>
                    <td>{{ i.id }}</td>
                    <td>{{ i.name }}</td>
                    <td>{{ i.description }}</td>
                    <td>{{ i.price }}</td>
                    <td>{{ i.discount }}</td>
                    <td>{{ i.Merchant_id }}</td>
                    <td>
                        <img src="/static/media/{{ i.image }} " alt="" width="150">
                    </td>
                    <td><a href="update_product/{{ i.id }}" class="btn btn-outline-info">Update</a></td>
                    <td><a href="delete_product/{{ i.id }}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}